// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PosLajuWebhookCapture.Data;

#nullable disable

namespace PosLajuWebhookCapture.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260618053053_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PosLajuWebhookCapture.Domains.CourierWebhookEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headers");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("processed");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_payload");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tracking_number");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_courier_webhook_events");

                    b.HasIndex("Processed")
                        .HasDatabaseName("ix_courier_webhook_events_processed");

                    b.HasIndex("TrackingNumber")
                        .HasDatabaseName("ix_courier_webhook_events_tracking_number");

                    b.ToTable("courier_webhook_events", (string)null);
                });

            modelBuilder.Entity("PosLajuWebhookCapture.Domains.CourierWebhookStatusUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourierWebhookEventId")
                        .HasColumnType("integer")
                        .HasColumnName("courier_webhook_event_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("EventTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_time_utc");

                    b.Property<string>("RawStatusCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("raw_status_code");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason_code");

                    b.Property<string>("ReasonDescription")
                        .HasColumnType("text")
                        .HasColumnName("reason_description");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tracking_number");

                    b.HasKey("Id")
                        .HasName("pk_courier_webhook_status_updates");

                    b.HasIndex("CourierWebhookEventId")
                        .HasDatabaseName("ix_courier_webhook_status_updates_courier_webhook_event_id");

                    b.HasIndex("TrackingNumber")
                        .HasDatabaseName("ix_courier_webhook_status_updates_tracking_number");

                    b.ToTable("courier_webhook_status_updates", (string)null);
                });

            modelBuilder.Entity("PosLajuWebhookCapture.Domains.CourierWebhookStatusUpdate", b =>
                {
                    b.HasOne("PosLajuWebhookCapture.Domains.CourierWebhookEvent", null)
                        .WithMany()
                        .HasForeignKey("CourierWebhookEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_courier_webhook_status_updates_courier_webhook_events_couri");
                });
#pragma warning restore 612, 618
        }
    }
}
